development:
  enabled: true
  requests_per_period: 50
  period_in_milliseconds: 3600000 # One hour

test:
  enabled: true
  requests_per_period: 50
  period_in_milliseconds: 3600000 # One hour

production:
  enabled: true
  requests_per_period: 50
  period_in_milliseconds: 3600000 # One hour

