development:
  url: 'redis://localhost:6379'

test:
  url: 'redis://localhost:6379'

# Setup for Heroku or Elasticache
production:
  url: <%= ENV['REDISTOGO_URL'] || ENV['REDIS_URL'] || 'redis://localhost:6379' %>

