aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] || 'us-east-1' %>

  # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Queue.html#receive_messages-instance_method
  receive_message:
    # # The number of seconds to wait for new messages when polling. Defaults to the #wait_time_seconds defined on the queue
    # wait_time_seconds: N 

    # TODO: Figure these out
    attribute_names:
      - ApproximateReceiveCount
      - SentTimestamp

# The number of allocated threads to process messages. Default 25
concurrency: 25

# The delay in seconds to pause a queue when it's empty. Default 0
delay: 25

queues:
  - [default, 1]

