# The number of allocated threads to process messages. Default 25
concurrency: 10

# The delay in seconds to pause a queue when it's empty. Default 0
delay: 25

queues:
  - ['<%= "#{ENV['SQS_QUEUE_PREFIX']}_default" %>', 1]
  - ['<%= "#{ENV['SQS_QUEUE_PREFIX']}_mailers" %>', 1]

